"""
GitHub Pull Request Operations

Provides PR management operations:
- Create PRs from agent patches
- Request reviews
- Add review comments
- Merge PRs
- Get PR diff
- Check PR status
"""

from typing import Any, Dict, List, Optional

from .client import GitHubClient


class PullRequestOperations:
    """
    GitHub Pull Request operations

    Handles all PR-related operations including creation,
    reviews, merging, and status checks.
    """

    def __init__(self, client: GitHubClient):
        """
        Initialize PR operations

        Args:
            client: GitHubClient instance
        """
        self.client = client

    async def create_pull_request(
        self,
        owner: str,
        repo: str,
        title: str,
        head: str,
        base: str,
        body: Optional[str] = None,
        draft: bool = False,
        maintainer_can_modify: bool = True,
    ) -> Dict[str, Any]:
        """
        Create a new pull request

        Args:
            owner: Repository owner
            repo: Repository name
            title: PR title
            head: Branch containing changes
            base: Branch to merge into
            body: PR description (markdown)
            draft: Create as draft PR
            maintainer_can_modify: Allow maintainer modifications

        Returns:
            Created PR data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls"
        payload = {
            "title": title,
            "head": head,
            "base": base,
            "draft": draft,
            "maintainer_can_modify": maintainer_can_modify,
        }

        if body:
            payload["body"] = body

        return await self.client.post(endpoint, json=payload)

    async def create_pr_from_patch(
        self,
        owner: str,
        repo: str,
        patch: str,
        branch_name: str,
        base_branch: str = "main",
        title: Optional[str] = None,
        description: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Create PR from agent-generated patch

        Args:
            owner: Repository owner
            repo: Repository name
            patch: Git patch content
            branch_name: Name for new branch
            base_branch: Base branch to merge into
            title: PR title
            description: PR description

        Returns:
            Created PR data with patch application info
        """
        # Note: This requires git operations which would typically be done
        # via a Git integration or GitHub's file API

        # Build PR description with patch info
        body_lines = []

        if description:
            body_lines.append(description)
            body_lines.append("")

        body_lines.extend([
            "## Changes",
            "This PR was generated from an agent patch.",
            "",
            "<details>",
            "<summary>View Patch</summary>",
            "",
            "```diff",
            patch,
            "```",
            "",
            "</details>",
            "",
            "---",
            "*Generated by AI Agent*",
        ])

        body = "\n".join(body_lines)

        return await self.create_pull_request(
            owner=owner,
            repo=repo,
            title=title or f"Agent patch: {branch_name}",
            head=branch_name,
            base=base_branch,
            body=body,
        )

    async def get_pull_request(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> Dict[str, Any]:
        """
        Get PR details

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            PR data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}"
        return await self.client.get(endpoint)

    async def list_pull_requests(
        self,
        owner: str,
        repo: str,
        state: str = "open",
        head: Optional[str] = None,
        base: Optional[str] = None,
        sort: str = "created",
        direction: str = "desc",
        per_page: int = 30,
    ) -> List[Dict[str, Any]]:
        """
        List repository pull requests

        Args:
            owner: Repository owner
            repo: Repository name
            state: PR state ("open", "closed", "all")
            head: Filter by head branch
            base: Filter by base branch
            sort: Sort by ("created", "updated", "popularity")
            direction: Sort direction ("asc", "desc")
            per_page: Results per page

        Returns:
            List of PRs
        """
        endpoint = f"/repos/{owner}/{repo}/pulls"
        params = {
            "state": state,
            "sort": sort,
            "direction": direction,
            "per_page": per_page,
        }

        if head:
            params["head"] = head
        if base:
            params["base"] = base

        return await self.client.paginate(endpoint, params=params, per_page=per_page)

    async def update_pull_request(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        title: Optional[str] = None,
        body: Optional[str] = None,
        state: Optional[str] = None,
        base: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Update a pull request

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            title: New title
            body: New body
            state: New state ("open" or "closed")
            base: New base branch

        Returns:
            Updated PR data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}"
        payload = {}

        if title is not None:
            payload["title"] = title
        if body is not None:
            payload["body"] = body
        if state is not None:
            payload["state"] = state
        if base is not None:
            payload["base"] = base

        return await self.client.patch(endpoint, json=payload)

    async def request_reviewers(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        reviewers: Optional[List[str]] = None,
        team_reviewers: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Request PR reviewers

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            reviewers: List of usernames
            team_reviewers: List of team slugs

        Returns:
            Updated PR data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers"
        payload = {}

        if reviewers:
            payload["reviewers"] = reviewers
        if team_reviewers:
            payload["team_reviewers"] = team_reviewers

        return await self.client.post(endpoint, json=payload)

    async def create_review(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        event: str,
        body: Optional[str] = None,
        comments: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        """
        Create a PR review

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            event: Review event ("APPROVE", "REQUEST_CHANGES", "COMMENT")
            body: Review body
            comments: List of review comments with path, position, and body

        Returns:
            Created review data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/reviews"
        payload = {"event": event}

        if body:
            payload["body"] = body
        if comments:
            payload["comments"] = comments

        return await self.client.post(endpoint, json=payload)

    async def add_review_comment(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        body: str,
        commit_id: str,
        path: str,
        line: Optional[int] = None,
        side: str = "RIGHT",
    ) -> Dict[str, Any]:
        """
        Add a review comment to a PR

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            body: Comment body
            commit_id: Commit SHA
            path: File path
            line: Line number (for single-line comments)
            side: Side of diff ("LEFT" or "RIGHT")

        Returns:
            Created comment data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/comments"
        payload = {
            "body": body,
            "commit_id": commit_id,
            "path": path,
            "side": side,
        }

        if line:
            payload["line"] = line

        return await self.client.post(endpoint, json=payload)

    async def get_pr_diff(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> str:
        """
        Get PR diff

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            Diff content
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}"

        # Request diff format
        import httpx

        url = f"{self.client.base_url}/repos/{owner}/{repo}/pulls/{pull_number}"
        headers = self.client._get_headers()
        headers["Accept"] = "application/vnd.github.v3.diff"

        async with httpx.AsyncClient(timeout=self.client.timeout) as client:
            response = await client.get(url, headers=headers)
            response.raise_for_status()
            return response.text

    async def get_pr_files(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> List[Dict[str, Any]]:
        """
        Get files changed in PR

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            List of changed files
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/files"
        return await self.client.paginate(endpoint)

    async def merge_pull_request(
        self,
        owner: str,
        repo: str,
        pull_number: int,
        commit_title: Optional[str] = None,
        commit_message: Optional[str] = None,
        merge_method: str = "merge",
    ) -> Dict[str, Any]:
        """
        Merge a pull request

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number
            commit_title: Merge commit title
            commit_message: Merge commit message
            merge_method: Merge method ("merge", "squash", "rebase")

        Returns:
            Merge result data
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/merge"
        payload = {"merge_method": merge_method}

        if commit_title:
            payload["commit_title"] = commit_title
        if commit_message:
            payload["commit_message"] = commit_message

        return await self.client.put(endpoint, json=payload)

    async def check_if_merged(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> bool:
        """
        Check if PR is merged

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            True if merged, False otherwise
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/merge"

        try:
            await self.client.get(endpoint)
            return True
        except Exception:
            return False

    async def get_pr_status(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> Dict[str, Any]:
        """
        Get PR status checks and reviews

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            Status information including checks and reviews
        """
        pr = await self.get_pull_request(owner, repo, pull_number)

        # Get commit status
        commit_sha = pr["head"]["sha"]
        status_endpoint = f"/repos/{owner}/{repo}/commits/{commit_sha}/status"
        status = await self.client.get(status_endpoint)

        # Get reviews
        reviews_endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/reviews"
        reviews = await self.client.get(reviews_endpoint)

        return {
            "pr": pr,
            "status": status,
            "reviews": reviews,
            "mergeable": pr.get("mergeable"),
            "mergeable_state": pr.get("mergeable_state"),
        }

    async def get_pr_commits(
        self,
        owner: str,
        repo: str,
        pull_number: int,
    ) -> List[Dict[str, Any]]:
        """
        Get commits in a PR

        Args:
            owner: Repository owner
            repo: Repository name
            pull_number: PR number

        Returns:
            List of commits
        """
        endpoint = f"/repos/{owner}/{repo}/pulls/{pull_number}/commits"
        return await self.client.paginate(endpoint)
