-- Seed data for agents table
-- Core AI agents in the system

INSERT INTO agents (
    name, display_name, description, agent_type, model_provider, model_name, model_version,
    capabilities, configuration, required_tools, max_tokens, temperature, is_active, version
) VALUES
    (
        'orchestrator',
        'Orchestrator',
        'Master orchestration agent that routes tasks to specialized sub-agents',
        'orchestrator',
        'anthropic',
        'claude-opus-4',
        '4.0',
        '{"routing": true, "task_decomposition": true, "priority_management": true, "cost_optimization": true}',
        '{"max_parallel_agents": 5, "timeout_seconds": 3600}',
        '["router", "priority_queue", "cost_calculator"]',
        8192,
        0.3,
        true,
        '1.0.0'
    ),
    (
        'architect',
        'Architect',
        'System design and architecture review agent',
        'architect',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"design_patterns": true, "scalability_analysis": true, "trade_off_analysis": true}',
        '{"focus_areas": ["performance", "security", "maintainability"]}',
        '["codebase_analyzer", "design_pattern_detector"]',
        4096,
        0.5,
        true,
        '1.0.0'
    ),
    (
        'planner',
        'Planner',
        'Project planning and sprint management agent',
        'planner',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"estimation": true, "dependency_tracking": true, "sprint_planning": true}',
        '{"estimation_method": "story_points", "sprint_length_days": 14}',
        '["task_analyzer", "dependency_graph"]',
        4096,
        0.4,
        true,
        '1.0.0'
    ),
    (
        'codegen',
        'Code Generator',
        'Generates code implementations from specifications',
        'codegen',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"language_support": ["python", "typescript", "java"], "framework_support": ["react", "fastapi", "spring"]}',
        '{"include_tests": true, "include_docs": true}',
        '["code_formatter", "linter"]',
        8192,
        0.7,
        true,
        '1.0.0'
    ),
    (
        'reviewer',
        'Code Reviewer',
        'Performs code review and quality assessment',
        'reviewer',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"code_quality": true, "security_review": true, "performance_review": true, "style_guide": true}',
        '{"min_approval_score": 7.0, "require_coverage": true}',
        '["static_analyzer", "security_scanner"]',
        4096,
        0.5,
        true,
        '1.0.0'
    ),
    (
        'tester',
        'QA Tester',
        'Test design, execution, and quality assurance',
        'tester',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"test_generation": true, "test_execution": true, "coverage_analysis": true}',
        '{"min_coverage": 80, "test_framework": "pytest"}',
        '["test_executor", "coverage_analyzer"]',
        4096,
        0.5,
        true,
        '1.0.0'
    ),
    (
        'security',
        'Security Agent',
        'Security analysis and vulnerability detection',
        'security',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"vulnerability_detection": true, "secret_detection": true, "dependency_scanning": true, "compliance": true}',
        '{"owasp_check": true, "cwe_check": true}',
        '["security_scanner", "dependency_checker", "secret_detector"]',
        4096,
        0.3,
        true,
        '1.0.0'
    ),
    (
        'deployer',
        'Deployment Agent',
        'Manages deployment and infrastructure provisioning',
        'deployer',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"deployment": true, "rollback": true, "monitoring": true}',
        '{"environments": ["staging", "production"], "blue_green_enabled": true}',
        '["docker", "kubernetes", "terraform"]',
        4096,
        0.4,
        true,
        '1.0.0'
    ),
    (
        'debugger',
        'Debugger',
        'Debugging and issue diagnosis agent',
        'debugger',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"error_analysis": true, "root_cause_analysis": true, "solution_recommendation": true}',
        '{"max_diagnosis_attempts": 5}',
        '["log_analyzer", "trace_inspector"]',
        4096,
        0.6,
        true,
        '1.0.0'
    ),
    (
        'documentation',
        'Documentation Agent',
        'Generates and maintains project documentation',
        'documentation',
        'anthropic',
        'claude-sonnet-4',
        '4.0',
        '{"api_docs": true, "user_guide": true, "architecture_docs": true}',
        '{"format": "markdown", "include_examples": true}',
        '["doc_generator", "markdown_formatter"]',
        4096,
        0.5,
        true,
        '1.0.0'
    )
ON CONFLICT (name) DO NOTHING;
